name: 'kubectl apply'
description: 'Deploy to Kubernetes with kubectl'
author: 'fergusn'
inputs: 
  filename:
    description: 'Filename that contains the configuration to apply'
runs:
  using: 'docker'
  image: 'docker://fergusn/kubectl:apply'
  args:
  - --filename
  - ${{ inputs.filename }}
